---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.11 webserver wordpress.4labs.example
        - 172.16.0.12 graylog
        - 172.16.0.13 kibana

    - name: Adiciona usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Criando diretório /home/suporte/swarm-lab
      synchronize:
        src: files/swarm-lab
        dest: /home/suporte

    - name: Instalando pacotes de dependencias para o curso de Kubernetes
      yum:
        name: ['unzip', 'wget', 'elinks', 'rsync', 'git', 'vim', 'yum-utils', 'device-mapper-persistent-data', 'lvm2']

    - name: Adiciona repositorio do Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Instala o Docker e suas dependencias
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Adiciona o usuario suporte no grupo docker
      user:
        name: suporte
        group: docker

    - name: Adiciona o usuario vagrant no grupo docker
      user:
        name: vagrant
        group: docker
        
    - name: Reinicia o Docker
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Inicializa o cluster Swarm
      shell: docker swarm init --advertise-addr 172.16.0.11
  
    - name: Cria a rede traefik
      shell: docker network create --driver=overlay traefik

    - name: Provisionar o Traefik e Wordpress no cluster Swarm
      shell: docker stack deploy -c /home/suporte/swarm-lab/wordpress-deploy.yaml traefik-wordpress
