---
- name: security
  box: ubuntu/bionic64
  hostname: security
  ipaddress: 172.16.0.11
  memory: 512
  cpus: 1
  provision: provision/ansible/security.yaml

- name: graylog
  box: debian/buster64
  hostname: graylog
  ipaddress: 172.16.0.12
  memory: 2560
  cpus: 1
  provision: provision/ansible/graylog.yaml

- name: kibana
  box: centos/7
  hostname: kibana
  ipaddress: 172.16.0.13
  memory: 2048
  cpus: 1
  provision: provision/ansible/kibana.yaml
